TELEGRAM_KEY_PRIMARY = "ENTER YOUR MAIN TELEGRAM BOT API KEY"
TELEGRAM_KEY_SECONDARY = "ENTER YOUR TESTING TELEGRAM BOT API KEY" # this is opotional you can enter a random str

PRIMARY_BOT_ID = "ENTER ID AS INTEGER"
SECONDARY_BOT_ID = "ENTER ID AS INTEGER" # this is opotional you can enter a random int

MONGODB_ATLAS_KEY = ""
SUPER_USER_COMMAND = "CREATING SUPER USER"